# Site settings
title: Mostafa Haggag
description: 'Personal Site'
url: 'http://thomas.zuehlke.family'
baseurl: ''
profilepic: '/images/mostafa.jpeg'
bkimage: '/images/cover.jpg'
# google_analytics: UA-XXXXXX-X
font_awesome: '/js/all.min.js'

author:
  name: 'Mostafa Haggag'
  email: mhaggaga@gmail.com
  #twitter_username: thomzuehlke
#  facebook_username: joshgerdes
#  github_username:  tzuehlke
  linkedin_username:  mostafa-haggag-0697543
 # meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
